sudo: false

jdk:
  - oraclejdk8

os: linux
dist: trusty
jdk: oraclejdk8
language: scala

matrix:
  include:
  - dist: precise
    jdk: openjdk6
    env: SBT_VERSION=0.13.17
    # https://github.com/travis-ci/travis-ci/issues/5227
    addons:
      hosts: workaround-travis-ci-issue-5227
      hostname: workaround-travis-ci-issue-5227

env:
  matrix:
    - SBT_VERSION=0.13.17
    - SBT_VERSION=1.0.4

before_script:
 - export JVM_OPTS="-Xms1024m -Xmx1024m -XX:ReservedCodeCacheSize=128m -Xss2m -Dfile.encoding=UTF-8"

script:
  - sbt "-no-colors" "^^ $SBT_VERSION" ";scalafmtTest;plugin/scripted;scaffold/scripted;lib/test"


