language: scala

sudo: false

script:
- jdk_switcher use openjdk6 && sbt "++ 2.10.6" "test:compile"
- jdk_switcher use oraclejdk8 && sbt "so test"

jdk:
  - oraclejdk8

before_script:
 - export JVM_OPTS="-Xms1024m -Xmx1024m -XX:ReservedCodeCacheSize=128m -XX:MaxPermSize=256m -Xss2m -Dfile.encoding=UTF-8"

after_success:
- export SBT_GHPAGES_COMMIT_MESSAGE="updated site https://github.com/foundweekends/giter8/commit/${TRAVIS_COMMIT}"
- if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == "0.7.x" && "${TRAVIS_REPO_SLUG}" == "foundweekends/giter8" ]]; then export PUBLISH_SITE=true; fi
- test "${PUBLISH_SITE}" == "true" && eval "$(ssh-agent -s)" #start the ssh agent
- test "${PUBLISH_SITE}" == "true" && openssl aes-256-cbc -K $encrypted_e5f9765ae931_key -iv $encrypted_e5f9765ae931_iv -in deploy_rsa.enc -out deploy_rsa -d
- test "${PUBLISH_SITE}" == "true" && chmod 600 deploy_rsa
- test "${PUBLISH_SITE}" == "true" && ssh-add deploy_rsa
- test "${PUBLISH_SITE}" == "true" && sbt pushSiteIfChanged

matrix:
  include:
  - dist: trusty
    group: edge
    sudo: required
    jdk: oraclejdk9
    script:
    # https://github.com/sbt/sbt/pull/2951
    - git clone https://github.com/retronym/java9-rt-export
    - cd java9-rt-export/
    - git checkout 1019a2873d057dd7214f4135e84283695728395d
    - jdk_switcher use oraclejdk8
    - sbt package
    - jdk_switcher use oraclejdk9
    - mkdir -p $HOME/.sbt/0.13/java9-rt-ext; java -jar target/java9-rt-export-*.jar $HOME/.sbt/0.13/java9-rt-ext/rt.jar
    - jar tf $HOME/.sbt/0.13/java9-rt-ext/rt.jar | grep java/lang/Object
    - cd ..
    - echo "sbt.version=0.13.14-RC2" > project/build.properties
    - wget https://raw.githubusercontent.com/paulp/sbt-extras/470e7ad01ee01ebb6dafa4902afe383c27222842/sbt && chmod +x ./sbt
    - ./sbt -Dscala.ext.dirs=$HOME/.sbt/0.13/java9-rt-ext ++$TRAVIS_SCALA_VERSION "so test"
    after_success:
