os: linux
dist: xenial
language: scala

jdk: openjdk8

stages:
  - name: test
  - name: push-pages
    if: (branch = master AND type = push) AND (repo = foundweekends/giter8)

matrix:
  include:
  - env: SBT_VERSION=1.2.8
    jdk: openjdk8
    script: sbt "-no-colors" "^^ $SBT_VERSION" ";publishLocal;scalafmtCheckAll;plugin/scripted;scaffold/scripted;lib/test;app/compile"
  - name: "Scala 2.13"
    script:
    - sbt "++ 2.13.2" app/test lib/test
  - env: SBT_VERSION=1.3.10
    jdk: openjdk11
    script: sbt "-no-colors" "^^ $SBT_VERSION" ";publishLocal;plugin/scripted;scaffold/scripted;lib/test;app/compile"
  - os: windows
    language: bash
    name: windows
    env:
    - JDK="adopt@1.8.0-252"
    script:
    - curl "https://raw.githubusercontent.com/DanySK/Gravis-CI/0a17947c034d1c7f5938ac7ec97e74b475eca399/.install-jdk-travis.sh" --output .install-jdk-travis.sh
    - source .install-jdk-travis.sh
    - wget https://raw.githubusercontent.com/paulp/sbt-extras/e252487b9bfdea6a6c/sbt && chmod +x ./sbt
    - ./sbt "-no-colors" "^^ 1.3.10" ";lib/test;app/test" # TODO enable scripted-test

before_script:
 - export JVM_OPTS="-Xms1024m -Xmx1024m -XX:ReservedCodeCacheSize=128m -Xss2m -Dfile.encoding=UTF-8"

jobs:
  include:
    - stage: push-pages
      script:
      - >
        export SBT_GHPAGES_COMMIT_MESSAGE="updated site https://github.com/foundweekends/giter8/commit/${TRAVIS_COMMIT}"
        export PUBLISH_SITE=true;
        eval "$(ssh-agent -s)" #start the ssh agent
        openssl aes-256-cbc \
          -K $encrypted_e5f9765ae931_key \
          -iv $encrypted_e5f9765ae931_iv \
          -in deploy_rsa.enc -out deploy_rsa -d
        chmod 600 deploy_rsa
        ssh-add deploy_rsa
        sbt pushSiteIfChanged
